name:                servant-generic-custom-monad
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/servant-generic-custom-monad#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - warp

executables:
  servant-generic-custom-monad:
    source-dirs:      src
    main:             Main.hs
    ghc-options: -Wall -Werror
